// Packs the crawled content bundle (../content) into the app so first launch
// is fully offline:
//   - src/content/seed.json          manifest + every story/page body inlined
//   - assets/content/images/*        cloth-art WebP files (copied)
//   - src/content/bundled-images.ts  static require() map so Metro bundles them
//
// Run whenever the content bundle changes:  npm run seed
// (CI runs it before every build, so store releases always carry fresh seed
// content; between releases the app updates itself over the air.)

import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const appDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const contentDir = path.resolve(appDir, '../content');

const manifest = JSON.parse(await fs.readFile(path.join(contentDir, 'manifest.json'), 'utf8'));

// Inline every story and page body (they are small; the whole seed is ~1.5MB).
const stories = {};
for (const [id, meta] of Object.entries(manifest.stories)) {
  stories[id] = JSON.parse(await fs.readFile(path.join(contentDir, meta.text.path), 'utf8'));
}
const pages = {};
for (const [id, meta] of Object.entries(manifest.pages)) {
  pages[id] = JSON.parse(await fs.readFile(path.join(contentDir, meta.text.path), 'utf8'));
}

await fs.mkdir(path.join(appDir, 'src/content'), { recursive: true });
await fs.writeFile(
  path.join(appDir, 'src/content/seed.json'),
  JSON.stringify({ manifest, stories, pages }),
);

// Copy images and emit the static require map (Metro needs literal paths).
const imgSrc = path.join(contentDir, 'images');
const imgDest = path.join(appDir, 'assets/content/images');
await fs.rm(imgDest, { recursive: true, force: true });
await fs.mkdir(imgDest, { recursive: true });
const files = (await fs.readdir(imgSrc)).filter((f) => f.endsWith('.webp')).sort();
for (const f of files) await fs.copyFile(path.join(imgSrc, f), path.join(imgDest, f));

const lines = files.map(
  (f) => `  'images/${f}': require('../../assets/content/images/${f}'),`,
);
await fs.writeFile(
  path.join(appDir, 'src/content/bundled-images.ts'),
  `// AUTO-GENERATED by scripts/generate-seed.mjs — do not edit by hand.
// Maps manifest image paths to Metro asset modules bundled with the app.
export const bundledImages: Record<string, number> = {
${lines.join('\n')}
};
`,
);

console.log(
  `Seed: ${Object.keys(stories).length} stories, ${Object.keys(manifest.videos ?? {}).length} videos, ` +
  `${files.length} images, contentVersion ${manifest.contentVersion}`,
);
